### ISSUE TITLE
Right Click Breaks Screen Saver Lock Screen During Suspend

### ISSUE THREAD

**Issue by FeralBytes** [linuxmint/cinnamon-screensaver#258]
```
 * Cinnamon-Screensaver version 3.6.1
 * Distribution - Mint 18.3
 * Graphics hardware NVidia GTX950M Driver = 384
 * 64 bit
 ```

##Issue
Screen saver is not locked upon resume from suspend when the right click menu is actively displayed in Nemo.
This is a security concern too.

##Steps to reproduce

    Right click in Nemo file manager; put the laptop into suspend by shutting the screen.
    Open the laptop screen.
    Observe that you can see your screen and that it is not locked.

##Expected behaviour
During step 3 the screen should be locked any ways.

##Other information
It may require Cinnamon to force a left click on the desktop to prevent a right click menu context from blocking the screen saver from taking over the screen.
Taken From Here: https://github.com/linuxmint/Cinnamon/issues/6676#issuecomment-352392949

**Comment by smurphos** [comment]
Can reproduce this consistently with Cinnamon 3.8.8, Cinnamon Screensaver 3.8.2. Ctrl-Alt-L has no effect if a context menu is visible (i've tried Chrome, Nemo and XED) and the machine fails to lock on suspend if laptop lid is closed with a context menu visible on screen. No sign of a cinnamon-screensaver crash, nor any relevant ./xsession-errors output.

Fresh install not an upgraded from 18.3 system

```
System:
  Host: HP-Pavilion-g6-Notebook-PC Kernel: 4.15.0-29-generic x86_64 bits: 64 
  compiler: gcc v: 7.3.0 Desktop: Cinnamon 3.8.8 Distro: Linux Mint 19 Tara 
  base: Ubuntu 18.04 LTS Bionic 
Graphics:
  Card-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 18.0.5 
  direct render: Yes
```
